#!/usr/bin/env python3
r'''
./p01A-missing-number
This program finds the missing number in a list of integers.
* by: Leomar Duran <https://github.com/lduran2>
* date: 2019-06-28T19:00ZQ
* for: https://dev.to/javinpaul/50-data-structure-and-algorithms-\
       problems-from-coding-interviews-4lh2
'''

import random # for picking the missing number
import logging # for logging
import sys # for command line arguments

def main(
    min = 1, # The minimum value in the array to generate
    max = 100, # The maximum value in the array to generate
    print = print # The printing function
):
    r'''
    Tests the find_missing function on a shuffled array from 1 to 100.
    '''
    # generate the list of numbers
    NUMBERS = generate_missing_number_list(min, max)
    # find the missing number
    MISSING = find_missing(NUMBERS, min, max)

    # The output:
    print(r'The array:')
    print(NUMBERS)
    print()
    print(r'The missing number is ', MISSING, r'.', sep=r'')

def find_missing(numbers, min, max):
    r'''
    Finds the number missing in the array of integers @numbers whose
    elements are in the interval [min, max].

    {1} Calculates the trapezoidal number from $k to $l.
    {2} Subtracts each number in the array from the trapezoidal
        number.
    {3} The resulting number is the missing number
    '''
    sum = trapezoidal_number(min, max) #{1}
    for x in numbers: #{2}
        sum -= x
    RESULT = sum #{3}
    return RESULT

def trapezoidal_number(k, l):
    r'''
    Calculates the trapezoidal number with rows from $k to $l.
    '''
    return (triangular_number(l) - triangular_number(k))

def triangular_number(k):
    r'''
    Calculates the triangular number with $k rows.
    '''
    return ((k*(k + 1)) >> 1)

def generate_missing_number_list(min, max):
    r'''
    Generates a list of shuffled numbers in the interval [min, max]
    with one number missing.

    {1} Chooses a random number in the interval [min, max[ to replace.
    {2} Creates an list in the interval [min, max[.
    {3} Replaces the random number [1] in the list with $max.
    {4} Shuffles the list.

    params:
        min -- the minimum value in the list
        max -- the maximum value in the list
    '''
    MISSING = random.randrange(min, max) #{1}
    logging.debug(r'Missing number chosen: %d', MISSING)
    numbers = list(range(min, max)) #{2}
    numbers[MISSING - min] = max #{3}
    random.shuffle(numbers) #{4}
    return numbers

if (r'__main__' == __name__):
    # if '--debug' flag was given in command line arguments,
    # place the logger in debug mode
    if (r'--debug' in sys.argv):
        logging.basicConfig(level=logging.DEBUG)
    main()
